# Generated by Django 5.0 on 2023-12-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(max_length=255)),
                ('open', models.JSONField()),
                ('close', models.JSONField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='knowledge_base.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='KEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(max_length=255)),
                ('occurance_condition', models.JSONField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='knowledge_base.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='KObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='knowledge_base.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='KRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(max_length=255)),
                ('condition', models.JSONField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='knowledge_base.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='KRuleElseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='else_instructions', to='knowledge_base.krule')),
            ],
        ),
        migrations.CreateModel(
            name='KRuleInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='knowledge_base.krule')),
            ],
        ),
        migrations.CreateModel(
            name='KType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(max_length=255)),
                ('meta', models.IntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Fuzzy')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='knowledge_base.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='KObjectAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='knowledge_base.kobject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attributes', to='knowledge_base.ktype')),
            ],
        ),
        migrations.CreateModel(
            name='KTypeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='knowledge_base.ktype')),
            ],
        ),
    ]
