# Generated by Django 5.0 on 2023-12-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kevent',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_events', to='knowledge_base.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='kinterval',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_intervals', to='knowledge_base.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='kobject',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_objects', to='knowledge_base.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='kobjectattribute',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ko_attributes', to='knowledge_base.kobject'),
        ),
        migrations.AlterField(
            model_name='kobjectattribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ko_attributes', to='knowledge_base.ktype'),
        ),
        migrations.AlterField(
            model_name='krule',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_rules', to='knowledge_base.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='kruleelseinstruction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr_else_instructions', to='knowledge_base.krule'),
        ),
        migrations.AlterField(
            model_name='kruleinstruction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr_instructions', to='knowledge_base.krule'),
        ),
        migrations.AlterField(
            model_name='ktype',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_types', to='knowledge_base.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='ktypevalue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kt_values', to='knowledge_base.ktype'),
        ),
    ]
