# Generated by Django 5.0.1 on 2024-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_kobject_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kevent',
            name='occurance_condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinterval',
            name='close',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinterval',
            name='open',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
