# Generated by Django 5.0.2 on 2024-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_alter_kevent_occurance_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krule',
            name='condition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
