# Generated by Django 5.0.3 on 2024-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_alter_krule_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobject',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
