# Generated by Django 5.0.3 on 2024-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0007_alter_kobject_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobject',
            name='group',
            field=models.CharField(blank=True, default='ГРУППА1', max_length=255, null=True),
        ),
    ]
